### ISSUE TITLE
[manifest.json not found] when uploading a zip that was also uploaded (and published) via chrome store

### ISSUE THREAD

**Issue by AlexDochioiu** [GoogleChromeLabs/extension-update-testing-tool#5]
<img width="803" alt="image" src="https://github.com/GoogleChromeLabs/extension-update-testing-tool/assets/38853913/94c66fb2-5841-414e-9aa8-f695b7407e95">

Running on macOS in case this matters.

**Comment by oliverdunk** [comment]
Hi @AlexDochioiu, do you see this with all extensions? As an example, it would be great if you could try downloading and using the hello world extension from here: https://play.web-extensions.dev/.

Assuming that does work, it would be great if you're comfortable sharing the .zip file (or an example of one that doesn't work) so I can try to reproduce. Thanks!

**Comment by AlexDochioiu** [comment]
Thanks for the quick reply:
a) Using the zip file for hello world works with no issues
b) Drag and dropping the unzipped directory instead seems to work fine 🤔 

[web.zip](https://github.com/GoogleChromeLabs/extension-update-testing-tool/files/15190028/web.zip)

**Comment by oliverdunk** [comment]
Thanks! It looks like this zip has a top-level folder (web/manifest.json etc.) which the Chrome Web Store handles but Chrome and the testing tool doesn't. I'm inclined not to fix this to match the behavior in Chrome - hopefully that makes sense though.

**Comment by GaurangTandon** [comment]
I ran into the same error just now 🙂 I agree it would be good to at least show a clear error message for this case, either in the README or in the UI itself.

**Comment by Jesper-Hustad** [comment]
**If anyone is reading this in the future here is how to solve the issue:**
Don't zip the folder containing your extension 
Instead go into the folder and select all the individual files and zip them.

<img width="544" alt="Image" src="https://github.com/user-attachments/assets/d4235f59-d242-4e47-8e99-7ee34220ebb8" />
