### ISSUE TITLE
"Could not establish connection. Receiving end does not exist." - Error calling chrome.runtime.sendMessage from website. Possibly as extension ID not the same.

### ISSUE THREAD

**Issue by humanismusic** [GoogleChromeLabs/extension-update-testing-tool#6]
## Expected Behavior

Sending messages via chrome.runtime.sendMessage works (is received by chrome.runtime.onMessageExternal in background.js). 
Can test all features including chrome.runtime.sendMessage and chrome.runtime.onMessageExternal.
IDs generated by this tool match the ID of the extension in the Chrome store

## Actual Behavior

Sending message from website to extension fails with message 'Could not establish connection. Receiving end does not exist.'. Likely because the ID created by the extension-update-testing-tool is not the same as the extension

## Steps to Reproduce the Problem

- Follow install manually process to generate extension.crx
- Drag to extensions page on chromium
- Initiate following function on website that is declared in externally_connectable section of manifest:

```
// from website to a static extension ID when website loads
chrome.runtime.sendMessage("anExtensionID", obj, (response) => {
                    // wait for response
                    
                    if (chrome.runtime.lastError) {
                        console.log("get-local-results error: ", chrome.runtime.lastError.message);
                        return;
                    }
                    
                    let response = response["results"];
                });
```

- Get error 'Could not establish connection. Receiving end does not exist.'

- Check extensions page in chromium and realize that the IDs are not the same

Is there a way to produce the correct extension ID that matches the one in the extension store or does this tool create a random extension ID each time? Or is there a workaround I may be missing?

Thanks

## Specifications

- Platform: windows

**Comment by oliverdunk** [comment]
Hi @humanismusic! Generating a CRX file with a matching ID to an extension in the store isn't possible for most extensions - in most cases, the Chrome Web Store manages your private key, and this is needed to sign a CRX.

With that in mind, the tool generates a new private key used just for testing, but that does unfortunately mean the ID changes.

One option you do have is setting the `WRITE_KEY` environment variable when running the tool, for example:

```sh
WRITE_KEY=1 npm start
```

This doesn't give you the same ID as the store but does make the ID consistent whenever you run the tool, which would allow you to setup your site to support a single additional ID.

Hope that helps!

**Comment by humanismusic** [comment]
Hi Oliver, 

Thanks for the quick reply. I've tried the WRITE_KEY=1 npm start solution (_set WRITE_KEY=1 && npm_ start for people on Windows) and it worked. Cheers

**Comment by oliverdunk** [comment]
That's great to hear! Thanks for following up.
